title:            Juan Sebastián Gómez Cañón
description:      "Juan Gómez is a M.Sc. Student at TU Ilmenau"
disqus_shortname: jsgc
reading_time:     true
words_per_minute: 200
#url:                    # blank for local preview
#url: http://ngpy.org   # for production
header-img: images/homepage.jpg
excerpt_separator: "<!--more-->"

# Owner/author information
owner:
  name:           Juan Sebastián Gómez Cañón
  avatar:         avatar.jpg
  bio:            "Juan Sebastián Gómez Cañön is completing his M.Sc. in Media Technology specializing in Audio Technology at the Technische Universität Ilmenau, Germany. He also completed a B.Sc. in Electronic Engineering and a B.A. in Music majoring in Audio Production at the Universidad de los Andes, Colombia. "
  email:          juan.sebastian.gomez.canon@idmt.fraunhofer.de
  # Social networking links used in footer. Update and remove as you like.
  twitter: 
  facebook:
  github: juansgomez87
  stackexchange:
  linkedin: 
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +mmistakes
  google_plus:

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics: UA-116955047-1  # Analytics Property ID
google_verify: # vCNYuIbRPqv4coJvcqQglEsd4IBd9p4cP0AdERyG86w  # Webmaster
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Berlin
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
  - jekyll-paginate
sass:
  sass_dir: _sass
  style: compressed

# http://jekyllrb.com/docs/permalinks/
permalink:   /:year/:month/:title  #/:categories/:title/

# Amount of post to show on home page
paginate: 5
paginate_path: "blog/page:num/"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  # use_coderay: true

  # coderay:
  #   coderay_line_numbers: inline
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
